/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Matthew' at '6/6/17 9:25 PM' with Gradle 3.0
 *
 * @author Matthew, @date 6/6/17 9:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
